import numpy as np
x=np.random.randint(1,1000,size=(4,4))
print(x)
print()
print(x[2:3:4,3:4:1])
a=(x[2:3:4,3:4:1])
a[0,0]=99
#changes made in a array reflects in original x array also
print()
print(a)
print(x)
#so to neglate this we neeed to use copy method
print()
b=(x[2:3:4,3:4:1]).copy()
print(b)
b[0,0]=100
print(b)
print(x)
print(b.shape)
np.random.seed(6)
print('for changeing the shape of the array')
y=np.random.randint(4,444,size=(3,4))
print(y)
print("now we reshape the array")
print(y.reshape(4,3))
np.random.seed(0)
print("concatenate")
e=np.random.randint(0,105,size=(2,3))
f=np.random.randint(4,555,size=(2,3))
print(e)
print()
print(f)
print("one below the another array")
print(np.concatenate([e,f]))
print('for beside')
print(np.concatenate([e,f],axis=1))
print('oneupon or one below')
print(np.vstack([e,f]))
print('for beside')
print(np.hstack([e,f]))
