import numpy as np
x=np.array(object=[1,2,3,4,5])

print(type(x))
x=np.array(object=[1,2,3,4,5],dtype=complex)
print(x)
print('')
#creation of numpyarray objects from scratch
zeros=np.zeros((4,5),"int")
print(zeros)
ones=np.ones((3,3))
print(ones)
ful=np.full(shape=(4,4),fill_value=44.56)
print(ful)
print()
arrange=np.arange(0,20,2)
print(arrange)
a=np.linspace(0,1,5)
print(a)
print( "for random values uniform distrubution ")
b=np.random.random((3,3))
print(b)
print('for normal distribution')
d=np.random.normal(0,1,(3,3))
print(d)
print('for desired range and size of arrays by numpy')
c= np.random.randint(10,1999,size=(3,2))
print(c)
print('for identity')
e=np.eye(4)
print(e)
print("to create numpy array object with uninitalized values")
f=np.empty(4)
print(f)