#mathematical operations on numoy arrays
import numpy as np
x=np.arange(4)
print(x)
print(x+2)
print(x-2)
print(x/2)
print(x*2)
print('floor division on the variable x')
print(x//2)
print('for modulus')
print(x%2)
print('for power')
print(x**2)
print(np.add(x,2))
print(np.subtract(x,4))
print('negation')
print(np.negative(x))
print(np.multiply(x,4))
print(np.floor_divide(x,5))
print('bollean indexing')
z=np.random.randint(10,500,size=(4,4))
print(z)
print(z>50)
print(z[z>50])
print(np.exp(z))
print()
print(np.exp2(z))
print()
print(np.log(z))
print()
print(np.sum(z))
print(np.var(z))
print(np.std(z))
print()
print(np.std(z,axis=0))
print(np.min(z))
print(np.max(z))
#for index position of max & minimum
print(np.argmin(z))
print(np.argmax(z))