#explicit and implicit slicing in pandas
import pandas as pd
data=pd.Series(["a","b","c","d"],index=[1,2,3,4])
print(data)
print("explicit index")
print(data[1])
print('but also behaves like a implicit index')
print(data[1:3])
print('to get out of this by special index attributes')
print(data.loc[1])
print(data.loc[1:3])
print('for implicit indexing by')
print(data.iloc[1])
print(data.iloc[1:3])
import numpy as np
np.random.seed(0)
array=np.random.randint(4,400,size=(4,5))
print(array)
df2=pd.DataFrame(array,index=list("abcd"),columns=("col1","col2","col3","col4","col5"))
print(df2)
print(df2["col1"])
df2["col6"]=df2["col2"]*df2["col3"]
print(df2)
print(df2['col6'])
print(df2.iloc[:1,:3])
print(df2.loc["a":"c","col1":"col4"])
print(df2[["col1","col2",'col3']])
print(df2)
print(df2[df2["col2"]>250])