import pandas as pd
import numpy as np
df_diabetes=pd.read_csv("diabetes.csv")
print()
print(df_diabetes.head())
print('To find is there any duplicates in the dataframe')
print(df_diabetes.duplicated())
print('To find duplicates for more specifically')
print(df_diabetes[df_diabetes.duplicated()])
print('for get to know how many no.of duplicates')
print(df_diabetes.duplicated().sum)
#to find  mising entries in the dataset we use isnull
print()
print(df_diabetes.isnull())
print(df_diabetes.isnull().any())
print('if any null value in total')
print(df_diabetes.isnull().any().any())
print('for no.of null values in the dataframe')
print(df_diabetes.isnull().sum())
print(df_diabetes.isnull().sum().sum())
#grouping operations and on top of it we can perform aggregation
print(df_diabetes.head())
print(df_diabetes["sex"].unique())#mean is the agegration here
print(df_diabetes.groupby("sex").mean())
print(df_diabetes.groupby("sex").agg(["mean", "max", "min"]))
print('to print index as column')
print(df_diabetes.reset_index())
print("for copy the dataframe")
df2_copy=df_diabetes.copy()
print(df2_copy)
print("we can drop some columns in the copied dataframe")
print(df2_copy.drop(["age","sex"],axis=1))
print("this  cant drop the inplace the dataframe to do that ")
df2_copy.drop(["age","sex"],axis=1,inplace=True)
print(df2_copy)
print(df2_copy.drop(columns=["bmi", "bp","s5"]))
